import streamlit as st
import pandas as pd
from pyecharts import options as opts
from pyecharts.charts import Bar
from streamlit_echarts import st_pyecharts
from pyecharts.charts import Pie
from pyecharts import options as opts
from pyecharts.charts import WordCloud
from pyecharts.globals import SymbolType

st.title('Exploratory Data Analysis')
@st.cache
def fetch(x):
    data = pd.read_csv(x,index_col=0)
    return data
@st.cache
def load_data():

    words = [
    ('could', 41),
    ('math', 4),
    ('datetime', 9),
    ('python', 433),
    ('add', 149),
    ('line', 97),
    ('multi', 18),
    ('donut', 1),
    ('graph', 29),
    ('plotly', 14),
    ('jinja', 3),
    ('template', 36),
    ('contert', 1),
    ('string', 215),
    ('dictionary', 44),
    ('program', 76),
    ('properly', 35),
    ('read', 93),
    ('text', 142),
    ('file', 447),
    ('create', 185),
    ('report', 12),
    ('specific', 105),
    ('value', 405),
    ('variable', 179),
    ('function', 377),
    ('loop', 133),
    ('record', 32),
    ('xml', 23),
    ('change', 177),
    ('canvas', 15),
    ('image', 199),
    ('download', 25),
    ('path', 56),
    ('adding', 66),
    ('shinydashboard', 1),
    ('header', 25),
    ('hide', 20),
    ('toggle', 9),
    ('button', 116),
    ('necessary', 2),
    ('host', 25),
    ('database', 105),
    ('php', 98),
    ('contact', 5),
    ('form', 97),
    ('best', 31),
    ('practice', 9),
    ('include', 18),
    ('within', 46),
    ('base', 12),
    ('class', 142),
    ('func', 2),
    ('return', 104),
    ('true', 15),
    ('run', 122),
    ('separate', 15),
    ('android', 125),
    ('studio', 61),
    ('two', 131),
    ('folder', 49),
    ('downloaded', 7),
    ('project', 80),
    ('memory', 47),
    ('allocated', 3),
    ('private', 9),
    ('even', 51),
    ('though', 17),
    ('mapped', 3),
    ('mmap', 4),
    ('jenkins', 18),
    ('bitbucket', 2),
    ('jira', 1),
    ('integration', 14),
    ('nextjs', 19),
    ('get', 289),
    ('object', 260),
    ('inject', 3),
    ('firebase', 76),
    ('instance', 36),
    ('isolate', 2),
    ('futurebuilder', 2),
    ('working', 142),
    ('flutter', 110),
    ('row', 107),
    ('indexing', 6),
    ('transaction', 7),
    ('across', 11),
    ('multiple', 214),
    ('daos', 1),
    ('jpa', 11),
    ('c', 180),
    ('recursive', 18),
    ('algorithm', 26),
    ('error', 533),
    ('using', 631),
    ('input', 139),
    ('trying', 87),
    ('make', 190),
    ('random', 38),
    ('number', 162),
    ('generator', 12),
    ('getting', 130),
    ('typeerror', 48),
    ('callable', 5),
    ('closed', 678),
    ('wrapping', 3),
    ('twice', 17),
    ('wrap', 4),
    ('ca', 128),
    ('back', 16),
    ('end', 30),
    ('data', 378),
    ('react', 191),
    ('app', 141),
    ('device', 32),
    ('macro', 10),
    ('generate', 39),
    ('struct', 22),
    ('parameter', 53),
    ('convert', 90),
    ('json', 101),
    ('geojson', 1),
    ('url', 68),
    ('endpoint', 13),
    ('table', 170),
    ('spreadsheet', 2),
    ('doc', 12),
    ('parsing', 13),
    ('changing', 46),
    ('border', 7),
    ('radius', 2),
    ('height', 17),
    ('mat', 4),
    ('select', 53),
    ('dropdown', 26),
    ('session', 16),
    ('timeout', 9),
    ('max', 15),
    ('per', 17),
    ('user', 170),
    ('spring', 69),
    ('boot', 45),
    ('application', 61),
    ('runtime', 15),
    ('google', 110),
    ('org', 3),
    ('chart', 28),
    ('java', 135),
    ('language', 31),
    ('help', 39),
    ('please', 28),
    ('task', 31),
    ('urgently', 1),
    ('correct', 25),
    ('way', 120),
    ('visualizing', 1),
    ('difference', 30),
    ('category', 9),
    ('median', 4),
    ('panda', 61),
    ('able', 42),
    ('import', 54),
    ('module', 76),
    ('api', 155),
    ('r', 83),
    ('sample', 14),
    ('seem', 11),
    ('painless', 1),
    ('mesh', 7),
    ('sometimes', 8),
    ('connect', 49),
    ('fetch', 32),
    ('ajax', 10),
    ('mvc', 12),
    ('expo', 10),
    ('refresh', 22),
    ('token', 45),
    ('custom', 80),
    ('validator', 1),
    ('cause', 15),
    ('lot', 5),
    ('break', 12),
    ('load', 55),
    ('node', 63),
    ('javafx', 8),
    ('update', 96),
    ('property', 71),
    ('javascript', 122),
    ('stop', 32),
    ('existing', 15),
    ('something', 11),
    ('happens', 9),
    ('duplicate', 382),
    ('vagrant', 1),
    ('wordpress', 37),
    ('vm', 9),
    ('db', 22),
    ('one', 151),
    ('retrieving', 6),
    ('match', 42),
    ('list', 240),
    ('disable', 19),
    ('autocomplete', 2),
    ('empty', 25),
    ('angular', 62),
    ('html', 81),
    ('content', 56),
    ('fully', 11),
    ('loaded', 9),
    ('page', 109),
    ('cloud', 30),
    ('storage', 21),
    ('local', 33),
    ('http', 40),
    ('request', 81),
    ('sending', 19),
    ('axios', 22),
    ('native', 47),
    ('method', 135),
    ('decorator', 3),
    ('setting', 23),
    ('csrf', 4),
    ('browser', 37),
    ('cooky', 7),
    ('tab', 12),
    ('inherit', 6),
    ('structs', 3),
    ('removing', 7),
    ('inside', 109),
    ('array', 291),
    ('center', 13),
    ('drawn', 3),
    ('problem', 132),
    ('decrypt', 3),
    ('code', 245),
    ('wrong', 45),
    ('key', 109),
    ('plotlyjs', 1),
    ('recreate', 2),
    ('shiny', 6),
    ('svg', 16),
    ('shape', 18),
    ('invert', 2),
    ('whats', 4),
    ('behind', 6),
    ('shopify', 3),
    ('blog', 5),
    ('bias', 1),
    ('preferential', 1),
    ('attachment', 1),
    ('network', 37),
    ('netlogo', 1),
    ('sql', 80),
    ('join', 27),
    ('appropriately', 1),
    ('sum', 37),
    ('mongo', 4),
    ('already', 24),
    ('findone', 1),
    ('giving', 25),
    ('wired', 2),
    ('result', 72),
    ('top', 23),
    ('ranking', 1),
    ('different', 110),
    ('place', 16),
    ('design', 12),
    ('swiftui', 36),
    ('hello', 5),
    ('know', 34),
    ('solve', 38),
    ('jetpack', 16),
    ('compose', 21),
    ('grid', 26),
    ('adaptive', 3),
    ('column', 178),
    ('based', 98),
    ('size', 37),
    ('j', 90),
    ('stack', 30),
    ('underflow', 1),
    ('pic', 1),
    ('assembly', 15),
    ('precise', 1),
    ('geometric', 4),
    ('extent', 1),
    ('ciimage', 1),
    ('video', 35),
    ('player', 9),
    ('progress', 8),
    ('bar', 33),
    ('behaves', 1),
    ('strange', 10),
    ('average', 16),
    ('trained', 3),
    ('model', 74),
    ('find', 104),
    ('city', 4),
    ('smallest', 5),
    ('neighbor', 2),
    ('threshold', 2),
    ('distance', 8),
    ('golang', 17),
    ('want', 69),
    ('certain', 33),
    ('information', 18),
    ('box', 24),
    ('winfroms', 1),
    ('choose', 7),
    ('knock', 1),
    ('dice', 1),
    ('game', 27),
    ('mongodb', 35),
    ('pymongo', 2),
    ('exists', 9),
    ('id', 38),
    ('drf', 5),
    ('try', 26),
    ('used', 33),
    ('nested', 50),
    ('serializer', 2),
    ('new', 89),
    ('nativeeventemitter', 2),
    ('building', 25),
    ('xcode', 16),
    ('many', 28),
    ('sha', 2),
    ('docker', 54),
    ('proper', 7),
    ('reuse', 4),
    ('doctrine', 3),
    ('dql', 2),
    ('prevent', 25),
    ('positional', 5),
    ('index', 46),
    ('xxx', 2),
    ('bound', 8),
    ('azure', 44),
    ('sdk', 11),
    ('use', 234),
    ('proxyoptions', 1),
    ('proxy', 15),
    ('pas', 55),
    ('required', 13),
    ('httpclient', 3),
    ('along', 4),
    ('hostname', 4),
    ('setup', 14),
    ('neuron', 1),
    ('perceptron', 2),
    ('chages', 1),
    ('question', 27),
    ('handle', 19),
    ('keypressed', 1),
    ('joomla', 1),
    ('timestring', 1),
    ('passed', 12),
    ('output', 88),
    ('call', 94),
    ('simplescalar', 1),
    ('cygwin', 2),
    ('deserialize', 4),
    ('correctly', 24),
    ('synchronized', 1),
    ('applied', 8),
    ('instead', 44),
    ('whole', 7),
    ('infinite', 10),
    ('bug', 6),
    ('laravel', 60),
    ('resource', 18),
    ('moving', 11),
    ('excluded', 1),
    ('arch', 3),
    ('individual', 5),
    ('package', 52),
    ('copy', 27),
    ('conditional', 15),
    ('formatting', 5),
    ('wise', 2),
    ('build', 91),
    ('unpack', 1),
    ('nonetype', 1),
    ('ga', 1),
    ('optimization', 3),
    ('set', 124),
    ('starting', 18),
    ('script', 74),
    ('another', 94),
    ('crash', 13),
    ('need', 70),
    ('message', 65),
    ('font', 18),
    ('openlayers', 2),
    ('feature', 19),
    ('style', 25),
    ('v', 49),
    ('layer', 17),
    ('stoping', 1),
    ('migrate', 3),
    ('live', 11),
    ('site', 22),
    ('machine', 22),
    ('diferent', 2),
    ('version', 40),
    ('element', 176),
    ('located', 3),
    ('selenium', 41),
    ('show', 87),
    ('awesome', 1),
    ('icon', 20),
    ('caused', 6),
    ('proxyerror', 1),
    ('remotedisconnected', 1),
    ('connection', 45),
    ('without', 99),
    ('response', 55),
    ('htaccess', 5),
    ('rewrite', 5),
    ('rule', 14),
    ('subdomain', 2),
    ('subfolder', 5),
    ('automapper', 4),
    ('mapping', 8),
    ('relationship', 19),
    ('constant', 8),
    ('char', 16),
    ('genius', 1),
    ('lyric', 1),
    ('opera', 1),
    ('extension', 24),
    ('scatterplot', 1),
    ('take', 37),
    ('argument', 62),
    ('given', 31),
    ('beginning', 4),
    ('running', 87),
    ('window', 112),
    ('making', 19),
    ('chat', 7),
    ('parser', 4),
    ('gui', 19),
    ('tkinter', 28),
    ('cant', 22),
    ('write', 50),
    ('overwriting', 2),
    ('rechart', 1),
    ('color', 45),
    ('opacity', 4),
    ('filter', 47),
    ('checkbox', 5),
    ('unexpected', 23),
    ('none', 15),
    ('domain', 17),
    ('name', 98),
    ('server', 141),
    ('deal', 6),
    ('joining', 2),
    ('child', 33),
    ('static', 22),
    ('linking', 6),
    ('clang', 4),
    ('libunwind', 1),
    ('cs', 53),
    ('quotation', 2),
    ('mark', 10),
    ('start', 43),
    ('byte', 16),
    ('unable', 73),
    ('pdf', 30),
    ('drive', 15),
    ('type', 175),
    ('side', 16),
    ('nav', 4),
    ('web', 49),
    ('subversion', 1),
    ('command', 63),
    ('client', 43),
    ('svn', 1),
    ('reference', 37),
    ('collection', 24),
    ('bingo', 1),
    ('specified', 12),
    ('writing', 13),
    ('dash', 8),
    ('clientside', 1),
    ('callback', 13),
    ('jupyter', 13),
    ('notebook', 12),
    ('pycharm', 10),
    ('calculating', 4),
    ('share', 8),
    ('price', 14),
    ('internal', 20),
    ('creation', 8),
    ('wizard', 2),
    ('remove', 65),
    ('symlink', 2),
    ('define', 17),
    ('simulating', 1),
    ('queue', 10),
    ('consumer', 8),
    ('tray', 2),
    ('restaurant', 3),
    ('koltin', 1),
    ('low', 8),
    ('quality', 3),
    ('registerforactivityresult', 1),
    ('penetration', 1),
    ('alert', 12),
    ('linux', 38),
    ('ubuntu', 19),
    ('binding', 11),
    ('iptyhon', 1),
    ('producing', 2),
    ('probability', 4),
    ('win', 4),
    ('crap', 1),
    ('downloading', 7),
    ('external', 25),
    ('iteration', 6),
    ('dynamically', 32),
    ('pathstring', 1),
    ('suddenly', 3),
    ('send', 39),
    ('email', 26),
    ('broker', 3),
    ('card', 8),
    ('dockerized', 1),
    ('gcp', 10),
    ('emulator', 10),
    ('bucket', 7),
    ('balancer', 3),
    ('helm', 2),
    ('terraform', 14),
    ('jump', 4),
    ('move', 27),
    ('depends', 1),
    ('uninitialized', 1),
    ('access', 86),
    ('stripe', 11),
    ('paymentintent', 3),
    ('aws', 39),
    ('sqs', 1),
    ('lambda', 24),
    ('postasync', 1),
    ('idle', 2),
    ('exactly', 12),
    ('mean', 23),
    ('sign', 10),
    ('open', 48),
    ('toast', 4),
    ('intent', 4),
    ('launch', 6),
    ('unescaped', 1),
    ('contains', 28),
    ('tag', 34),
    ('structure', 24),
    ('develop', 5),
    ('fabric', 3),
    ('mod', 2),
    ('listview', 10),
    ('showing', 43),
    ('thread', 29),
    ('exit', 12),
    ('early', 5),
    ('hbox', 1),
    ('clicking', 12),
    ('display', 72),
    ('vbox', 1),
    ('incorrect', 12),
    ('direction', 5),
    ('apperate', 1),
    ('workspace', 4),
    ('iex', 1),
    ('character', 52),
    ('position', 37),
    ('fixed', 6),
    ('width', 21),
    ('dropped', 2),
    ('item', 77),
    ('rendering', 24),
    ('mcp', 1),
    ('minecraft', 1),
    ('django', 93),
    ('built', 7),
    ('password', 33),
    ('reset', 13),
    ('split', 19),
    ('vertical', 3),
    ('range', 48),
    ('widget', 22),
    ('displaying', 18),
    ('availability', 3),
    ('throughout', 1),
    ('day', 13),
    ('piece', 3),
    ('jvm', 4),
    ('instruction', 6),
    ('swap', 7),
    ('aaa', 1),
    ('automation', 4),
    ('test', 77),
    ('failed', 64),
    ('express', 16),
    ('vps', 3),
    ('go', 23),
    ('compile', 14),
    ('got', 19),
    ('issue', 88),
    ('append', 13),
    ('attribute', 45),
    ('auth', 12),
    ('pervent', 1),
    ('swagger', 3),
    ('generating', 11),
    ('responseentity', 1),
    ('real', 10),
    ('single', 31),
    ('entity', 27),
    ('link', 43),
    ('together', 9),
    ('haskell', 9),
    ('lazyness', 1),
    ('evaluation', 2),
    ('order', 54),
    ('pattern', 24),
    ('matching', 15),
    ('mappedby', 1),
    ('unknown', 17),
    ('target', 17),
    ('default', 24),
    ('length', 17),
    ('io', 31),
    ('reliably', 1),
    ('pinia', 1),
    ('state', 51),
    ('component', 85),
    ('macos', 26),
    ('ventura', 6),
    ('save', 50),
    ('framework', 23),
    ('scala', 8),
    ('spark', 11),
    ('extract', 30),
    ('logic', 16),
    ('aggregation', 6),
    ('collision', 6),
    ('detector', 2),
    ('circle', 11),
    ('next', 23),
    ('serve', 2),
    ('statically', 1),
    ('regular', 10),
    ('expression', 21),
    ('exchange', 3),
    ('gal', 1),
    ('field', 84),
    ('insert', 40),
    ('mysql', 68),
    ('pipeline', 13),
    ('hi', 8),
    ('locate', 5),
    ('chromedriver', 2),
    ('thanks', 2),
    ('advance', 3),
    ('semantic', 2),
    ('ui', 26),
    ('horizontal', 7),
    ('menu', 25),
    ('overflowing', 1),
    ('testlink', 1),
    ('installation', 12),
    ('performance', 18),
    ('readability', 4),
    ('level', 20),
    ('library', 62),
    ('supportwalletfragment', 2),
    ('xamarin', 9),
    ('keyframe', 2),
    ('fill', 10),
    ('safari', 5),
    ('train', 5),
    ('simpy', 2),
    ('simulation', 8),
    ('rllib', 2),
    ('full', 19),
    ('extend', 7),
    ('vector', 24),
    ('rust', 22),
    ('caesar', 1),
    ('cipher', 3),
    ('markdownit', 1),
    ('deploying', 11),
    ('kubernetes', 8),
    ('pod', 8),
    ('gave', 2),
    ('implement', 33),
    ('socket', 19),
    ('connects', 2),
    ('always', 24),
    ('till', 2),
    ('close', 14),
    ('basis', 2),
    ('calculate', 30),
    ('executed', 6),
    ('libreoffice', 2),
    ('virtual', 13),
    ('environment', 12),
    ('relative', 10),
    ('scaled', 1),
    ('dragged', 1),
    ('around', 10),
    ('solving', 4),
    ('plotting', 10),
    ('render', 16),
    ('artifact', 4),
    ('mac', 16),
    ('outlinepass', 1),
    ('redirect', 26),
    ('login', 29),
    ('nvim', 1),
    ('overriding', 3),
    ('ftplugin', 1),
    ('neovim', 4),
    ('capacity', 1),
    ('rebalance', 1),
    ('spot', 4),
    ('paper', 3),
    ('introduced', 2),
    ('kernel', 12),
    ('convolutional', 3),
    ('neural', 9),
    ('bot', 36),
    ('work', 137),
    ('russian', 1),
    ('ukranian', 1),
    ('increase', 9),
    ('incremental', 3),
    ('rendered', 4),
    ('although', 5),
    ('come', 9),
    ('right', 34),
    ('specify', 12),
    ('github', 33),
    ('action', 28),
    ('fatal', 6),
    ('goroutines', 1),
    ('asleep', 1),
    ('deadlock', 2),
    ('reading', 33),
    ('vectorized', 1),
    ('frame', 19),
    ('picker', 2),
    ('heroku', 10),
    ('push', 17),
    ('parse', 23),
    ('procfile', 2),
    ('tried', 5),
    ('suggested', 2),
    ('solution', 13),
    ('mysqli', 4),
    ('query', 110),
    ('oops', 1),
    ('sort', 31),
    ('min', 7),
    ('put', 23),
    ('dataframe', 69),
    ('missing', 33),
    ('debian', 6),
    ('purpose', 5),
    ('documentation', 8),
    ('sorted', 6),
    ('expected', 28),
    ('found', 53),
    ('int', 19),
    ('graphql', 13),
    ('testing', 19),
    ('float', 20),
    ('statement', 46),
    ('ada', 1),
    ('various', 2),
    ('csv', 39),
    ('force', 5),
    ('route', 31),
    ('wait', 12),
    ('finish', 4),
    ('uploading', 10),
    ('click', 47),
    ('listener', 8),
    ('uncaught', 19),
    ('null', 56),
    ('iterable', 5),
    ('symbol', 17),
    ('mock', 7),
    ('dependency', 31),
    ('abstract', 4),
    ('shortcut', 3),
    ('desktop', 10),
    ('give', 49),
    ('mail', 5),
    ('pimcore', 1),
    ('symfony', 5),
    ('amlalinux', 1),
    ('hosting', 8),
    ('website', 47),
    ('cloudflare', 5),
    ('store', 34),
    ('received', 10),
    ('prop', 12),
    ('encoding', 9),
    ('learning', 12),
    ('mariadb', 10),
    ('scrollbar', 2),
    ('vuetify', 4),
    ('customize', 3),
    ('hotspot', 1),
    ('ssid', 1),
    ('stuck', 13),
    ('wificonfiguration', 1),
    ('among', 4),
    ('dont', 10),
    ('receiving', 6),
    ('integrating', 2),
    ('blazor', 12),
    ('keycloak', 4),
    ('photo', 9),
    ('incorrectly', 4),
    ('containing', 22),
    ('facing', 4),
    ('installtion', 1),
    ('gfortran', 1),
    ('compiler', 12),
    ('slot', 4),
    ('outlook', 5),
    ('sub', 10),
    ('calendar', 12),
    ('attached', 2),
    ('connecting', 17),
    ('inconsistent', 3),
    ('passing', 28),
    ('blocked', 5),
    ('understanding', 6),
    ('book', 6),
    ('example', 10),
    ('updating', 30),
    ('cell', 26),
    ('datasets', 4),
    ('onclick', 9),
    ('localstorage', 5),
    ('dataset', 20),
    ('intention', 1),
    ('persistence', 3),
    ('red', 5),
    ('const', 5),
    ('returning', 49),
    ('anything', 8),
    ('junit', 7),
    ('generated', 19),
    ('authentication', 20),
    ('service', 33),
    ('invalid', 34),
    ('group', 41),
    ('accessing', 15),
    ('pyspark', 15),
    ('univariatefeatureselector', 1),
    ('every', 43),
    ('nth', 2),
    ('oracle', 13),
    ('instant', 1),
    ('parallel', 6),
    ('bypass', 4),
    ('recent', 6),
    ('telegram', 15),
    ('limitation', 4),
    ('discord', 22),
    ('long', 19),
    ('indicate', 2),
    ('updated', 14),
    ('equation', 7),
    ('expand', 7),
    ('increasing', 4),
    ('numeric', 10),
    ('consecutively', 1),
    ('terminal', 19),
    ('block', 39),
    ('routing', 11),
    ('codegniter', 1),
    ('current', 26),
    ('admin', 9),
    ('security', 10),
    ('manager', 11),
    ('exception', 41),
    ('creating', 68),
    ('schedule', 6),
    ('notification', 11),
    ('kotlin', 24),
    ('volle', 1),
    ('decompile', 3),
    ('apk', 5),
    ('trouble', 12),
    ('importing', 14),
    ('flask', 23),
    ('dance', 1),
    ('subdomains', 1),
    ('expire', 2),
    ('short', 2),
    ('time', 119),
    ('exe', 6),
    ('made', 14),
    ('pyinstaller', 6),
    ('assign', 11),
    ('dask', 3),
    ('captcha', 1),
    ('separately', 4),
    ('nfv', 1),
    ('vanet', 1),
    ('protocol', 8),
    ('trim', 3),
    ('fetched', 4),
    ('designer', 3),
    ('everything', 4),
    ('manually', 11),
    ('helped', 1),
    ('tool', 11),
    ('construction', 1),
    ('async', 21),
    ('wont', 7),
    ('construct', 5),
    ('void', 6),
    ('become', 3),
    ('resolve', 28),
    ('configuration', 15),
    ('debugruntimeclasspath', 2),
    ('dolphin', 1),
    ('determine', 9),
    ('msvc', 2),
    ('gcc', 6),
    ('intel', 4),
    ('processor', 2),
    ('redux', 16),
    ('ssr', 2),
    ('loading', 22),
    ('mobile', 13),
    ('drupal', 1),
    ('tailwind', 7),
    ('visual', 31),
    ('assigning', 10),
    ('high', 11),
    ('polymorphism', 1),
    ('processing', 9),
    ('sagemaker', 7),
    ('dropping', 1),
    ('generalization', 1),
    ('step', 11),
    ('wpf', 9),
    ('bootstrap', 26),
    ('theme', 9),
    ('internet', 8),
    ('grouping', 7),
    ('latest', 9),
    ('article', 3),
    ('computing', 1),
    ('loss', 9),
    ('cucumber', 2),
    ('scenario', 4),
    ('main', 22),
    ('pil', 2),
    ('pillow', 1),
    ('console', 29),
    ('wifi', 3),
    ('centos', 1),
    ('case', 21),
    ('genetic', 3),
    ('taking', 10),
    ('converge', 1),
    ('organize', 4),
    ('selectizeinput', 2),
    ('dependecies', 2),
    ('reverse', 9),
    ('edit', 15),
    ('option', 29),
    ('phonebook', 1),
    ('shell', 15),
    ('big', 9),
    ('pixel', 9),
    ('small', 12),
    ('tile', 1),
    ('infer', 2),
    ('schema', 7),
    ('several', 14),
    ('zip', 7),
    ('synchronizing', 1),
    ('listwheelscrollview', 1),
    ('view', 47),
    ('upload', 29),
    ('look', 5),
    ('ad', 10),
    ('core', 35),
]   

    return words

load = load_data()
tag = fetch('tag2.csv')
data = fetch('a1123.csv')
data2 = fetch('testdd.csv')
data3 = fetch('test_d.csv')

data = pd.DataFrame(load,columns=['word','frequency']).sort_values(by='frequency',ascending=False)
data = data.head(10)


def page1():

    s = tag.groupby(['tag'])['id'].count().sort_values(ascending=False).reset_index(name='count').head(20)
    s1 = data2.groupby(['tag'])['id'].count().sort_values(ascending=False).reset_index(name='count').head(20)

    x = (
        Bar()
        .add_xaxis(s1['tag'].tolist())
        .add_yaxis("All title", s1['count'].tolist())
        .set_global_opts(
            title_opts=opts.TitleOpts(),
            datazoom_opts=[opts.DataZoomOpts(), opts.DataZoomOpts(type_="inside")],
        )
    )

    s3 = (
        Bar()
        .add_xaxis(s['tag'].tolist())
        .add_yaxis("1 day ago", s['count'].tolist(),color='blue')
        .set_global_opts(
            title_opts=opts.TitleOpts(),
            datazoom_opts=[opts.DataZoomOpts(), opts.DataZoomOpts(type_="inside")],
        )
    )

    #
    col8, col9, col10 = st.columns(3)
    col8.metric("All", "7500", )
    col9.metric("1 day ago", "2334", "31.12%")

    col10.metric("Total frequence of word", f"{data['frequency'].sum()}")
    col1, col3 = st.columns([3,1])

    with col1:
        st.header("Popular tag ")
        st_pyecharts(x)

    with col3:
        st.header("List top 20")
        st.write(s1)


    col0, col00 = st.columns([1,3])

    with col0:
        st.header("List top 20 ")
        st.write(s)
    with col00:
        st.header("Popular tag (1 day ago)")
        st_pyecharts(s3)




    x_data = ["Score -", "Score +" , "No Score"]
    y_data = [1746, 824, 4930]
    data_pair = [list(z) for z in zip(x_data, y_data)]
    data_pair.sort(key=lambda x: x[1])

    ss = (
        Pie()
        .add(
            "",
            [list(z) for z in zip(x_data, y_data)],
            radius=["35%", "75%"],
        )
        .set_global_opts(
            title_opts=opts.TitleOpts(),
            legend_opts=opts.LegendOpts(orient="vertical", pos_top="15%", pos_left="2%"),
        )
        .set_series_opts(label_opts=opts.LabelOpts(formatter="{b} : {d}%"))

    )


    aa1 = (
        Bar()
        .add_xaxis(data.word.tolist())
        .add_yaxis("All title", data.frequency.tolist(),color='green')
        .reversal_axis()
        .set_series_opts(label_opts=opts.LabelOpts(position="right"))
        .set_global_opts(title_opts=opts.TitleOpts())
    )


    c1 = (
        WordCloud()
        .add("", load, word_size_range=[10,100], shape=SymbolType.DIAMOND)
        .set_global_opts(title_opts=opts.TitleOpts(title="Frequence word"))
        
    )

    col4, col5 = st.columns([2,1])

    with col4:
        st.header("Total Score of questions ")
        st_pyecharts(ss)
    with col5:
        st.markdown("""meaning

        Score + is Vote that more zero 
    Score - is Vote that less zero 
    No Score is No interactions
    
    """)
    x_data = ["No Answer", "Answer"]
    y_data = [4508, 2992,]
    data_pair = [list(z) for z in zip(x_data, y_data)]
    data_pair.sort(key=lambda x: x[1])

    zxc = (
        Pie()
        .add(
            "",
            [list(z) for z in zip(x_data, y_data)],
            radius=["35%", "75%"],
        )
        .set_global_opts(
            title_opts=opts.TitleOpts(),
            legend_opts=opts.LegendOpts(orient="vertical", pos_top="15%", pos_left="2%"),
        )
        .set_series_opts(label_opts=opts.LabelOpts(formatter="{b} : {d}%"))

    )
    col11, col12 = st.columns([2,1])

    with col11:
        st.header("Total Asnwer of questions ")
        st_pyecharts(zxc)
    with col12:
        st.markdown("""meaning

        Asnwer is question has answer
    No Asnwer is question hasn't answer 
    
    """)

    st.header("Word Cloud")
    st_pyecharts(c1)
    st.header("Word of frequence 10 top")
    st_pyecharts(aa1)
    

def page2():
    st.write(data3)
    x_data = ["No Answer", "Answer"]
    y_data = [4508, 2992,]
    data_pair = [list(z) for z in zip(x_data, y_data)]
    data_pair.sort(key=lambda x: x[1])

    zxc = (
        Pie()
        .add(
            "",
            [list(z) for z in zip(x_data, y_data)],
            radius=["35%", "75%"],
        )
        .set_global_opts(
            title_opts=opts.TitleOpts(),
            legend_opts=opts.LegendOpts(orient="vertical", pos_top="15%", pos_left="2%"),
        )
        .set_series_opts(label_opts=opts.LabelOpts(formatter="{b} : {d}%"))

    )
    st_pyecharts(zxc)

page_names_to_funcs = {
    "Homepage": page1,
    "Answer": page2,
}

selected_page = st.sidebar.selectbox("Select a page", page_names_to_funcs.keys())
page_names_to_funcs[selected_page]()